CREATE USER SA PASSWORD "" ADMIN
/*C1*/CONNECT USER sa PASSWORD ""
create table ROOM (url varchar(255), username varchar(255), userip varchar(255), PRIMARY KEY (url, username))
create index url on ROOM(url)
create table MOVEMENT (room varchar(255), obj varchar(255), x0 real, y0 real, z0 real, x1 real, y1 real, z1 real)
create index obj on MOVEMENT(obj)
INSERT INTO ROOM VALUES('http://www.yahoo.com/','suhit','128.59.23.58')
INSERT INTO ROOM VALUES('http://www.navy.mil/','suhit','128.59.23.58')
INSERT INTO MOVEMENT VALUES('http://www.navy.mil/','http://www.navy.mil/navyjobs.gif',0.0,0.0,0.0,1.2684517,0.0,19.203163)
